/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type MenufullscreenOverridesProps = {
    Menufullscreen?: PrimitiveOverrideProps<ViewProps>;
    "02Search"?: PrimitiveOverrideProps<ViewProps>;
    ToolsStatusBar?: PrimitiveOverrideProps<ViewProps>;
    Background?: PrimitiveOverrideProps<ViewProps>;
    statusbar?: PrimitiveOverrideProps<ViewProps>;
    time?: PrimitiveOverrideProps<ViewProps>;
    Time?: PrimitiveOverrideProps<TextProps>;
    battery?: PrimitiveOverrideProps<ViewProps>;
    bounds172481862?: PrimitiveOverrideProps<IconProps>;
    Shape172481863?: PrimitiveOverrideProps<IconProps>;
    cellular?: PrimitiveOverrideProps<ViewProps>;
    bounds172481865?: PrimitiveOverrideProps<IconProps>;
    Shape172481866?: PrimitiveOverrideProps<IconProps>;
    wifi?: PrimitiveOverrideProps<ViewProps>;
    bounds172481868?: PrimitiveOverrideProps<IconProps>;
    Shape172481869?: PrimitiveOverrideProps<IconProps>;
    Path?: PrimitiveOverrideProps<IconProps>;
    Path13?: PrimitiveOverrideProps<IconProps>;
    Logo?: PrimitiveOverrideProps<ViewProps>;
    "icons8-notepad-961"?: PrimitiveOverrideProps<ImageProps>;
    SharedSearchBar?: PrimitiveOverrideProps<ViewProps>;
    InputField?: PrimitiveOverrideProps<IconProps>;
    Placeholder?: PrimitiveOverrideProps<TextProps>;
    Search24Regular?: PrimitiveOverrideProps<ViewProps>;
    Color172481853?: PrimitiveOverrideProps<IconProps>;
    "01ProfilePicture"?: PrimitiveOverrideProps<ViewProps>;
    Delete24Regular169083913?: PrimitiveOverrideProps<ViewProps>;
    Sharedinmenu169083914?: PrimitiveOverrideProps<ViewProps>;
    Sharedinmenu169083915?: PrimitiveOverrideProps<ViewProps>;
    Person24Regular169083916?: PrimitiveOverrideProps<ViewProps>;
    Tasksinmenu169083917?: PrimitiveOverrideProps<ViewProps>;
    Checkmark24Regular169083918?: PrimitiveOverrideProps<ViewProps>;
    Remindersinmenu169083919?: PrimitiveOverrideProps<ViewProps>;
    "icons8-notification-241169083920"?: PrimitiveOverrideProps<ImageProps>;
    Notebookinmenu169083921?: PrimitiveOverrideProps<ViewProps>;
    "icons8-journal-501169083922"?: PrimitiveOverrideProps<ImageProps>;
    Mynotesinmenu?: PrimitiveOverrideProps<ViewProps>;
    "icons8-list-view-161169083924"?: PrimitiveOverrideProps<ImageProps>;
    Rectangle3?: PrimitiveOverrideProps<ViewProps>;
    Quickaddballoon?: PrimitiveOverrideProps<ViewProps>;
    Ellipse1?: PrimitiveOverrideProps<IconProps>;
    Add24Filled?: PrimitiveOverrideProps<ViewProps>;
    Color172481855?: PrimitiveOverrideProps<IconProps>;
    Rectangle4?: PrimitiveOverrideProps<IconProps>;
    John?: PrimitiveOverrideProps<TextProps>;
    "01Dividers169083931"?: PrimitiveOverrideProps<ViewProps>;
    "01Dividers172481529"?: PrimitiveOverrideProps<ViewProps>;
    Color172481530?: PrimitiveOverrideProps<ViewProps>;
    Title?: PrimitiveOverrideProps<TextProps>;
    description?: PrimitiveOverrideProps<TextProps>;
    Color169083935?: PrimitiveOverrideProps<IconProps>;
    Sharedinmenu169083936?: PrimitiveOverrideProps<ViewProps>;
    Sharedinmenu169083937?: PrimitiveOverrideProps<ViewProps>;
    Person24Regular169083938?: PrimitiveOverrideProps<ViewProps>;
    Tasksinmenu169083939?: PrimitiveOverrideProps<ViewProps>;
    Checkmark24Regular169083940?: PrimitiveOverrideProps<ViewProps>;
    Flag24Regular?: PrimitiveOverrideProps<ViewProps>;
    SharedHandle?: PrimitiveOverrideProps<ViewProps>;
    Handle?: PrimitiveOverrideProps<ViewProps>;
    Menu?: PrimitiveOverrideProps<TextProps>;
    "01Dividers17255517"?: PrimitiveOverrideProps<ViewProps>;
    Color17255518?: PrimitiveOverrideProps<ViewProps>;
    Rectangle5?: PrimitiveOverrideProps<ViewProps>;
    Rectangle7?: PrimitiveOverrideProps<ViewProps>;
    Rectangle9?: PrimitiveOverrideProps<ViewProps>;
    Rectangle6?: PrimitiveOverrideProps<ViewProps>;
    Rectangle8?: PrimitiveOverrideProps<ViewProps>;
    Rectangle10?: PrimitiveOverrideProps<ViewProps>;
    Mynotes?: PrimitiveOverrideProps<TextProps>;
    Tasks?: PrimitiveOverrideProps<TextProps>;
    Shared?: PrimitiveOverrideProps<TextProps>;
    Reminders?: PrimitiveOverrideProps<TextProps>;
    Notebook?: PrimitiveOverrideProps<TextProps>;
    Deleted?: PrimitiveOverrideProps<TextProps>;
    Remindersinmenu169083985?: PrimitiveOverrideProps<ViewProps>;
    "icons8-notification-241169083986"?: PrimitiveOverrideProps<ImageProps>;
    Tasksinmenu169083991?: PrimitiveOverrideProps<ViewProps>;
    Checkmark24Regular169083992?: PrimitiveOverrideProps<ViewProps>;
    Notebookinmenu169083993?: PrimitiveOverrideProps<ViewProps>;
    "icons8-journal-501169083994"?: PrimitiveOverrideProps<ImageProps>;
    Sharedinmenu169083988?: PrimitiveOverrideProps<ViewProps>;
    Sharedinmenu169083989?: PrimitiveOverrideProps<ViewProps>;
    Person24Regula?: PrimitiveOverrideProps<ViewProps>;
    Delete24Regular172481850?: PrimitiveOverrideProps<ViewProps>;
    Color172481851?: PrimitiveOverrideProps<IconProps>;
    "icons8-list-view-161169083996"?: PrimitiveOverrideProps<ImageProps>;
    iconbelloutline?: PrimitiveOverrideProps<ViewProps>;
    Vector170023856?: PrimitiveOverrideProps<IconProps>;
    Vector170023857?: PrimitiveOverrideProps<IconProps>;
    iconbookoutline?: PrimitiveOverrideProps<ViewProps>;
    Vector170023859?: PrimitiveOverrideProps<IconProps>;
    Vector170023860?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type MenufullscreenProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: MenufullscreenOverridesProps | undefined | null;
}>;
export default function Menufullscreen(props: MenufullscreenProps): React.ReactElement;
